### ISSUE TITLE
[Feature]: Clarify state of the project in the README

### ISSUE THREAD

**Issue by greimel** [JuliaPluto/PlutoDesktop#25]
### In which process do you want a new feature?

Something else

### Feature / Improvement

The new semester has started and many students will start using Pluto for their classes. Since this repo has such a prominent place (and such a promising name) I think it would be nice if you clarified some things in the README.

In particular,

1. what platforms are supported (only Windows, I suppose?) and when this is going to change
2. what kind of users should already use this (mainly Pluto developers, I suppose?)
3. redirect all other users to the installation and usage instructions of the Pluto.jl repo

### Version

0.0.1-alpha

**Comment by Illusion47586** [comment]
I hope this solves the issue! Feel free to reopen this issue if you want!
