### ISSUE TITLE
[Feature]: Using the default Julia installation instead of portable from assets

### ISSUE THREAD

**Issue by mmikhasenko** [JuliaPluto/PlutoDesktop#40]
### In which process do you want a new feature?

Julia Installation

### Feature / Improvement

It would be great if one does not need to download a new version of Julia (https://github.com/JuliaPluto/PlutoDesktop/issues/38#issuecomment-1272551449),
using instead the one available in the `PATH`.

It would add a flexibility for versions of Julia and Pluto for users who use Julia already.

### Version

0.0.2

**Comment by fonsp** [comment]
Hi @mmikhasenko !

Thanks for the suggestion, we definitely understand why users would want to use their own Julia version.

Currently, we made the decision to not support this feature in PlutoDesktop: you will only be able to use the bundled version of Julia. The motivation here is that our initial focus with PlutoDesktop is to make Pluto's setup as easy and robust as possible, which means bundling Julia in the installation. We want to first achieve this goal, and after we have a rock solid experience, we can look into more functionality.

Note that we will continue to support the regular Pluto.jl package on Windows through the Pkg manager. This will let you use a custom Julia version, Pluto version, configuration, etc. For advanced users, this is the way to go, while the PlutoDesktop app is there in parallel, to serve a more general audience.
