### ISSUE TITLE
[Feature]: Capability to specify a julia setup

### ISSUE THREAD

**Issue by curio-sitas** [JuliaPluto/PlutoDesktop#44]
### In which process do you want a new feature?

Julia Installation

### Feature / Improvement

It would be interesting to choose wether to let the installer to install julia or choose an already installed julia version.

### Version

0.0.2

**Comment by fonsp** [comment]
Thanks for the suggestion! Take a look at https://github.com/JuliaPluto/PlutoDesktop/issues/40#issuecomment-1273168057
