### ISSUE TITLE
Remove react dependency

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/PlutoDesktop#49]
We have almost no frontend code in this codebase, so we can probably get rid of the react dependency.

**Comment by fonsp** [comment]
It would be **great** if we can also avoid webpack and configuration. Maybe switch from electron-builder to https://www.electronforge.io/ ? They recently became the "official" electron builder, migrating from github.com/electron-userland to github.com/electron

**Comment by ctrekker** [comment]
Removing webpack could be trickier than I anticipated, since it handles all the typescript compilation and module management
