### ISSUE TITLE
Fix npm audits

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/PlutoDesktop#52]
There are a couple of security vulnerabilities

(Having fewer dependencies would make these less likely 🌝)

**Comment by fonsp** [comment]
See https://github.com/JuliaPluto/PlutoDesktop/security/dependabot for all alerts

**Comment by ctrekker** [comment]
Pretty sure all is well with this now - not sure what it was that fixed it but I removed a LOT of dependencies

**Comment by fonsp** [comment]
Yessss thanks!!
