### ISSUE TITLE
URL or path detection needs some revision

### ISSUE THREAD

**Issue by fonsp** [JuliaPluto/PlutoDesktop#62]
`path_or_url.startswith("http")` is not so foolproof. Let's see what we use in the Pluto frontend and copy that :)

**Comment by ctrekker** [comment]
I think this issue is outdated, but there's still some work to be done on the "Open a notebook" UI styling and input verification
![image](https://user-images.githubusercontent.com/22894011/235249552-c4aa6f69-bf35-45ae-a524-7e5191e09b66.png)
